name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - dask=2.12
  - dask-ml=1.2
  - featuretools=0.13
  - hvplot=0.5
  - imbalanced-learn=0.6
  - ipython-sql=0.3
  - jupyterlab=1.2
  - jupyterlab-git=0.9
  - lightgbm=2.3
  - matplotlib=3.2
  - nbdime=1.1
  - nodejs=13
  - numba=0.48
  - optuna=1.2
  - pandas=1.0
  - pip=20.0
  - pip:
    - -r file:requirements.txt
  - pyarrow=0.16
  - python=3.7
  - scikit-learn=0.22
  - xgboost=1.0
