name: null

channels:
  - intel
  - conda-forge
  - defaults

dependencies:
  - bokeh
  - dask
  - dask-ml
  - featuretools
  - gh
  - git
  - holoviews
  - hvplot
  - imbalanced-learn
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - lightgbm
  - matplotlib
  - numba
  - optuna
  - pandas
  - panel
  - pip
  - pip:
    - -r file:requirements.txt
  - pyarrow
  - python
  - pyviz_comms
  - scikit-learn
  - umap-learn
  - xeus-python
  - xgboost
